---
- name: Get Web Console route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: openshift-console
    name: console
  register: r_console_route

- name: Get API server URL
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: r_api_url

# ARGOCD
- name: Get the ArgoCD console route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: openshift-gitops-server
    namespace: openshift-gitops
  register: r_argocd_console_route

- name: Get the ArgoCD admin password
  k8s_info:
    api_version: v1
    kind: Secret
    name: openshift-gitops-cluster
    namespace: openshift-gitops
  register: r_argocd_admin_password

- name: Set fact for ArgoCD route
  set_fact:
    argocd_route: "{{ r_argocd_console_route | json_query(route_query) }}"
  vars:
  - route_query: resources[].spec.host|[0]

- name: Set fact for ArgoCD admin passwd
  set_fact:
    argocd_passwd: "{{ r_argocd_admin_password | json_query(secret_query) | b64decode }}"
  vars:
  - secret_query: resources[].data."admin.password"|[0]

# QUAY
- name: Get the QUAY console route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: quay-registry-quay
    namespace: openshift-operators
  register: r_quay_console_route

- name: Set fact for Quay route
  set_fact:
    quay_route: "{{ r_quay_console_route | json_query(route_query) }}"
  vars:
  - route_query: resources[].spec.host|[0]

- name: Print user info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
  - ""
  - "Your ArgoCD console is available at:"
  - "https://{{ argocd_route }}"
  - "The ArgoCD's admin password is: {{ argocd_passwd }}"
  - ""
  - "Your ACS central is available at:"
  - "https://{{ acs_route }}"
  - "The ACS' central admin password is: {{ acs_passwd }}"
  - ""
  - "Your Quay console is available at:"
  - "https://{{ quay_route }}"
  - ""

- name: Save user data
  agnosticd_user_info:
    data:
      web_console_url: "https://{{ r_console_route.resources[0].spec.host }}"
      api_url: "{{ r_api_url.resources[0].status.apiServerURL }}"
      argocd_url: "https://{{ r_argocd_console_route.resources[0].spec.host }}"
      argocd_adminpasswd: "{{ argocd_passwd }}"
      acs_url: "https://{{ acs_route }}"
      acs_adminpasswd: "{{ acs_passwd }}"
      quay_url: "https://{{ quay_route }}"

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
